/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Sarausad
 */
public class Admin_landing extends javax.swing.JFrame {

    /**
     * Creates new form Admin_landing
     */
    public Admin_landing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orientationButtonGroup = new javax.swing.ButtonGroup();
        sortButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        helloTextField = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        logoutButton = new javax.swing.JButton();
        salesReportButton = new javax.swing.JButton();
        idRadioButton = new javax.swing.JRadioButton();
        typeRadioButton = new javax.swing.JRadioButton();
        dateAddedRadioButton = new javax.swing.JRadioButton();
        firstNameRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lastNameRadioButton = new javax.swing.JRadioButton();
        updateEmployeeButton = new javax.swing.JButton();
        addEmployeeButton = new javax.swing.JButton();
        removeEmployeeButton = new javax.swing.JButton();
        descendingRadioButton = new javax.swing.JRadioButton();
        ascendingRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(630, 550));
        jPanel1.setLayout(null);

        helloTextField.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        helloTextField.setText("Hello, <username>");
        jPanel1.add(helloTextField);
        helloTextField.setBounds(10, 10, 160, 18);

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Last Name", "First Name", "Address ", "Email", "Birthday", "Contact Number", "Date Added", "Added By", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 600, 290);

        logoutButton.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        logoutButton.setText("Logout");
        jPanel1.add(logoutButton);
        logoutButton.setBounds(530, 550, 73, 25);

        salesReportButton.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        salesReportButton.setText("Sales Report");
        jPanel1.add(salesReportButton);
        salesReportButton.setBounds(240, 510, 150, 25);

        sortButtonGroup.add(idRadioButton);
        idRadioButton.setFont(new java.awt.Font("Meiryo UI", 0, 11)); // NOI18N
        idRadioButton.setText("ID");
        jPanel1.add(idRadioButton);
        idRadioButton.setBounds(60, 400, 50, 23);

        sortButtonGroup.add(typeRadioButton);
        typeRadioButton.setFont(new java.awt.Font("Meiryo UI", 0, 11)); // NOI18N
        typeRadioButton.setText("Type");
        jPanel1.add(typeRadioButton);
        typeRadioButton.setBounds(520, 400, 51, 23);

        sortButtonGroup.add(dateAddedRadioButton);
        dateAddedRadioButton.setFont(new java.awt.Font("Meiryo UI", 0, 11)); // NOI18N
        dateAddedRadioButton.setText("Date Added");
        jPanel1.add(dateAddedRadioButton);
        dateAddedRadioButton.setBounds(400, 400, 87, 23);

        sortButtonGroup.add(firstNameRadioButton);
        firstNameRadioButton.setFont(new java.awt.Font("Meiryo UI", 0, 11)); // NOI18N
        firstNameRadioButton.setText("First Name");
        jPanel1.add(firstNameRadioButton);
        firstNameRadioButton.setBounds(270, 400, 90, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 362, 600, 10);

        jLabel2.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        jLabel2.setText("Sort by");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 380, 50, 16);

        sortButtonGroup.add(lastNameRadioButton);
        lastNameRadioButton.setFont(new java.awt.Font("Meiryo UI", 0, 11)); // NOI18N
        lastNameRadioButton.setText("Last Name");
        jPanel1.add(lastNameRadioButton);
        lastNameRadioButton.setBounds(140, 400, 81, 23);

        updateEmployeeButton.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        updateEmployeeButton.setText("Update Employee");
        jPanel1.add(updateEmployeeButton);
        updateEmployeeButton.setBounds(400, 470, 150, 25);

        addEmployeeButton.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        addEmployeeButton.setText("Add Employee");
        jPanel1.add(addEmployeeButton);
        addEmployeeButton.setBounds(80, 470, 150, 25);

        removeEmployeeButton.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        removeEmployeeButton.setText("Remove Employee");
        jPanel1.add(removeEmployeeButton);
        removeEmployeeButton.setBounds(240, 470, 150, 25);

        orientationButtonGroup.add(descendingRadioButton);
        descendingRadioButton.setFont(new java.awt.Font("Meiryo UI", 0, 11)); // NOI18N
        descendingRadioButton.setText("Descending");
        jPanel1.add(descendingRadioButton);
        descendingRadioButton.setBounds(310, 430, 87, 23);

        orientationButtonGroup.add(ascendingRadioButton);
        ascendingRadioButton.setFont(new java.awt.Font("Meiryo UI", 0, 11)); // NOI18N
        ascendingRadioButton.setText("Ascending");
        jPanel1.add(ascendingRadioButton);
        ascendingRadioButton.setBounds(200, 430, 87, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_landing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JRadioButton ascendingRadioButton;
    private javax.swing.JRadioButton dateAddedRadioButton;
    private javax.swing.JRadioButton descendingRadioButton;
    private javax.swing.JTable employeeTable;
    private javax.swing.JRadioButton firstNameRadioButton;
    private javax.swing.JLabel helloTextField;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton lastNameRadioButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.ButtonGroup orientationButtonGroup;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JButton salesReportButton;
    private javax.swing.ButtonGroup sortButtonGroup;
    private javax.swing.JRadioButton typeRadioButton;
    private javax.swing.JButton updateEmployeeButton;
    // End of variables declaration//GEN-END:variables
}
